all: part_1 part_2

debug: debug_1 debug_2

part_1:
	gcc part1.c -o part1.out

part_2:
	gcc part2.c -o part2.out

debug_1:
	gcc part1.c -g -o debug1.out

debug_2:
	gcc part2.c -g -o debug2.out

clean:
	rm *.out

